import { MaterialIcons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { useMemo, useState } from "react";
import { FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { Avatar, palette, PrimaryButton, SectionCard } from "@/components/meshline-ui";
import { ScreenContainer } from "@/components/screen-container";
import { haptic } from "@/lib/haptics";
import { useMeshline } from "@/lib/meshline-context";

type SpaceKind = "group" | "channel";

export default function NewSpaceScreen() {
  const router = useRouter();
  const { createSpace, state } = useMeshline();
  const [mode, setMode] = useState<"choose" | SpaceKind>("choose");
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [members, setMembers] = useState<string[]>([]);
  const [error, setError] = useState("");
  const [creating, setCreating] = useState(false);
  const selectedContacts = useMemo(() => state.contacts.filter((contact) => members.includes(contact.username)), [members, state.contacts]);
  const toggleMember = (username: string) => setMembers((current) => current.includes(username) ? current.filter((value) => value !== username) : [...current, username]);
  const create = async () => {
    if (mode === "choose") return;
    if (title.trim().length < 2) { setError("Give your space a name with at least 2 characters."); haptic.warning(); return; }
    setCreating(true); setError("");
    const id = await createSpace(mode, title, description, members);
    haptic.success(); router.replace({ pathname: "/chat/[id]", params: { id } });
  };

  if (mode === "choose") return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F6F7FB]" className="bg-[#F6F7FB]"><View style={styles.chooseContent}><View style={styles.header}><Pressable onPress={() => router.back()} hitSlop={10} style={styles.back}><MaterialIcons name="arrow-back" size={22} color={palette.ink} /></Pressable><Text style={styles.title}>Create</Text><View style={styles.back} /></View><Text style={styles.subtitle}>Start a direct conversation, a private group, or a one-to-many channel.</Text><Pressable onPress={() => router.push("/new-chat")} style={({ pressed }) => [styles.choice, pressed && styles.pressed]}><View style={styles.choiceIcon}><MaterialIcons name="chat-bubble-outline" size={23} color={palette.indigo} /></View><View style={styles.choiceCopy}><Text style={styles.choiceTitle}>New chat</Text><Text style={styles.choiceText}>Message one saved person by @username</Text></View><MaterialIcons name="chevron-right" size={22} color="#A0A9B9" /></Pressable><Pressable onPress={() => setMode("group")} style={({ pressed }) => [styles.choice, pressed && styles.pressed]}><View style={styles.choiceIcon}><MaterialIcons name="group" size={24} color={palette.indigo} /></View><View style={styles.choiceCopy}><Text style={styles.choiceTitle}>New group</Text><Text style={styles.choiceText}>A local shared space where members can chat</Text></View><MaterialIcons name="chevron-right" size={22} color="#A0A9B9" /></Pressable><Pressable onPress={() => setMode("channel")} style={({ pressed }) => [styles.choice, pressed && styles.pressed]}><View style={styles.choiceIcon}><MaterialIcons name="campaign" size={24} color={palette.indigo} /></View><View style={styles.choiceCopy}><Text style={styles.choiceTitle}>New channel</Text><Text style={styles.choiceText}>A local broadcast space with owner-only posts</Text></View><MaterialIcons name="chevron-right" size={22} color="#A0A9B9" /></Pressable></View></ScreenContainer>;

  const isGroup = mode === "group";
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F6F7FB]" className="bg-[#F6F7FB]"><FlatList data={state.contacts} keyExtractor={(item) => item.id} contentContainerStyle={styles.formContent} ListHeaderComponent={<><View style={styles.header}><Pressable onPress={() => setMode("choose")} hitSlop={10} style={styles.back}><MaterialIcons name="arrow-back" size={22} color={palette.ink} /></Pressable><Text style={styles.title}>New {isGroup ? "group" : "channel"}</Text><View style={styles.back} /></View><Text style={styles.subtitle}>{isGroup ? "Invite saved contacts into a shared local text conversation." : "Create a broadcast space. In this MVP, you are the only local author."}</Text><SectionCard style={styles.formCard}><Text style={styles.label}>{isGroup ? "GROUP NAME" : "CHANNEL NAME"}</Text><TextInput value={title} onChangeText={setTitle} placeholder={isGroup ? "Weekend plans" : "Product updates"} placeholderTextColor="#9AA3B4" maxLength={60} style={styles.input} /><Text style={styles.label}>DESCRIPTION (OPTIONAL)</Text><TextInput value={description} onChangeText={setDescription} placeholder={isGroup ? "What this group is for" : "What this channel publishes"} placeholderTextColor="#9AA3B4" multiline maxLength={180} style={[styles.input, styles.descriptionInput]} /></SectionCard><Text style={styles.memberHeading}>{isGroup ? "ADD MEMBERS" : "INITIAL SUBSCRIBERS"}</Text><Text style={styles.memberHint}>{selectedContacts.length ? `${selectedContacts.length} selected` : "Select contacts now, or add people later when network transport exists."}</Text></>} renderItem={({ item }) => { const selected = members.includes(item.username); return <Pressable onPress={() => toggleMember(item.username)} style={({ pressed }) => [styles.memberRow, selected && styles.memberSelected, pressed && styles.pressed]}><Avatar label={item.displayName} size={42} tone="emerald" /><View style={styles.memberCopy}><Text style={styles.memberName}>{item.displayName}</Text><Text style={styles.memberUsername}>{item.username}</Text></View><MaterialIcons name={selected ? "check-circle" : "add-circle-outline"} size={22} color={selected ? palette.indigo : "#9DA6B6"} /></Pressable>; }} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="people-outline" size={27} color="#A0A9B9" /><Text style={styles.emptyText}>No saved contacts yet. You can still create this local space.</Text></View>} ListFooterComponent={<View style={styles.footer}>{error ? <Text style={styles.error}>{error}</Text> : null}<PrimaryButton label={creating ? "Creating…" : `Create ${isGroup ? "group" : "channel"}`} icon={isGroup ? "group" : "campaign"} onPress={create} disabled={creating || title.trim().length < 2} /></View>} /></ScreenContainer>;
}

const styles = StyleSheet.create({ chooseContent: { flex: 1, padding: 20, paddingTop: 13 }, formContent: { padding: 20, paddingTop: 13, paddingBottom: 34, flexGrow: 1 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, back: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center" }, title: { color: palette.ink, fontSize: 18, lineHeight: 24, fontWeight: "800" }, subtitle: { color: palette.muted, fontSize: 14, lineHeight: 20, marginTop: 20, marginBottom: 19 }, choice: { minHeight: 79, flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: palette.line, borderRadius: 18, padding: 14, marginBottom: 10 }, choiceIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: palette.indigoSoft, alignItems: "center", justifyContent: "center" }, choiceCopy: { flex: 1 }, choiceTitle: { color: palette.ink, fontSize: 16, lineHeight: 21, fontWeight: "800" }, choiceText: { color: palette.muted, fontSize: 12, lineHeight: 17, marginTop: 2 }, formCard: { padding: 16 }, label: { color: "#7B8598", fontSize: 11, lineHeight: 15, fontWeight: "800", letterSpacing: 1.05, marginBottom: 7, marginTop: 12 }, input: { height: 48, borderRadius: 14, borderColor: "#DDE2EC", borderWidth: 1, backgroundColor: "#FFFFFF", color: palette.ink, fontSize: 15, paddingHorizontal: 13 }, descriptionInput: { height: 72, paddingTop: 10, textAlignVertical: "top" }, memberHeading: { color: "#8B95A7", fontSize: 11, lineHeight: 16, fontWeight: "800", letterSpacing: 1.05, marginTop: 23, marginLeft: 3 }, memberHint: { color: palette.muted, fontSize: 12, lineHeight: 17, marginTop: 3, marginBottom: 8, marginLeft: 3 }, memberRow: { minHeight: 64, flexDirection: "row", alignItems: "center", gap: 11, padding: 10, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: palette.line }, memberSelected: { backgroundColor: "#F0F2FF", borderRadius: 14, borderBottomWidth: 0 }, memberCopy: { flex: 1 }, memberName: { color: palette.ink, fontSize: 15, lineHeight: 20, fontWeight: "700" }, memberUsername: { color: palette.muted, fontSize: 12, lineHeight: 16, marginTop: 1 }, empty: { alignItems: "center", paddingVertical: 28, paddingHorizontal: 42 }, emptyText: { color: palette.muted, fontSize: 13, lineHeight: 18, textAlign: "center", marginTop: 7 }, footer: { marginTop: 24 }, error: { color: palette.coral, fontSize: 13, lineHeight: 18, fontWeight: "700", marginBottom: 9 }, pressed: { opacity: 0.68 } });
