import { MaterialIcons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, Platform, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";

import { palette, SectionCard } from "@/components/meshline-ui";
import { ScreenContainer } from "@/components/screen-container";
import { getOrCreateTransportDeviceKey, transportFingerprint } from "@/lib/transport";
import { useMeshline } from "@/lib/meshline-context";

export default function TransportLabScreen() {
  const router = useRouter();
  const { identity } = useMeshline();
  const [fingerprint, setFingerprint] = useState("");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    void getOrCreateTransportDeviceKey().then((key) => setFingerprint(transportFingerprint(key.publicKey))).finally(() => setLoading(false));
  }, []);

  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-[#F6F7FB]" className="bg-[#F6F7FB]"><View style={styles.header}><Pressable onPress={() => router.back()} hitSlop={10} style={({ pressed }) => [styles.back, pressed && styles.pressed]}><MaterialIcons name="arrow-back" size={22} color={palette.ink} /></Pressable><Text style={styles.headerTitle}>Encrypted text proof</Text><View style={styles.headerSpacer} /></View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator><SectionCard style={styles.alert}><MaterialIcons name="science" size={22} color={palette.indigo} /><View style={styles.alertCopy}><Text style={styles.alertTitle}>Experimental relay path</Text><Text style={styles.alertText}>Direct text messages can use device-held box keys and an opaque development relay. This is a proof of concept, not production E2EE: it does not yet provide X3DH, ratcheting, identity verification, or durable relay storage.</Text></View></SectionCard><Text style={styles.sectionTitle}>THIS DEVICE</Text><SectionCard style={styles.keyCard}><Text style={styles.label}>LOCAL USERNAME</Text><Text style={styles.username}>{identity?.username ?? "No local identity"}</Text><Text style={styles.label}>TRANSPORT KEY FINGERPRINT</Text>{loading ? <ActivityIndicator color={palette.indigo} style={styles.loader} /> : <Text selectable style={styles.fingerprint}>{fingerprint}</Text>}<Text style={styles.caption}>Compare fingerprints outside Meshline before treating a contact key as trusted. A browser preview is not a secure key-storage environment; test on two installed phones.</Text></SectionCard><Text style={styles.sectionTitle}>TWO-PHONE CHECK</Text><SectionCard style={styles.steps}><Step number="1" text="Install or open this same build on Phone A and Phone B, then create separate local Meshline identities." /><Step number="2" text="Open this screen on both phones once. Each device registers only its public relay key; its private key remains on that device." /><Step number="3" text="Save the other person as a contact using their exact @username. Compare the displayed key fingerprints over a trusted channel." /><Step number="4" text="Send a direct text from Phone A. The relay receives a nonce, ciphertext, and routing metadata; Phone B polls, authenticates, and decrypts the envelope locally." /><Step number="5" text="Turn off Phone B, send a text, then reopen it. The in-memory development relay should release the queued ciphertext while it remains running." /></SectionCard><Text style={styles.note}>Platform: {Platform.OS}. The relay is intentionally transient for this test. A restart clears its queue and public device directory. No media is supported.</Text></ScrollView></ScreenContainer>;
}

function Step({ number, text }: { number: string; text: string }) { return <View style={styles.step}><View style={styles.stepNumber}><Text style={styles.stepNumberText}>{number}</Text></View><Text style={styles.stepText}>{text}</Text></View>; }

const styles = StyleSheet.create({ header: { minHeight: 64, backgroundColor: "#FFFFFF", borderBottomColor: palette.line, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", alignItems: "center", paddingHorizontal: 14 }, back: { width: 37, height: 37, borderRadius: 12, alignItems: "center", justifyContent: "center" }, headerTitle: { flex: 1, textAlign: "center", color: palette.ink, fontSize: 17, lineHeight: 22, fontWeight: "800" }, headerSpacer: { width: 37 }, content: { padding: 18, paddingTop: 17, paddingBottom: 42 }, alert: { flexDirection: "row", alignItems: "flex-start", gap: 11, padding: 16 }, alertCopy: { flex: 1 }, alertTitle: { color: palette.ink, fontSize: 15, lineHeight: 20, fontWeight: "800" }, alertText: { color: palette.muted, fontSize: 12, lineHeight: 17, marginTop: 3 }, sectionTitle: { color: "#8B95A7", fontSize: 11, lineHeight: 16, fontWeight: "800", letterSpacing: 1.05, marginTop: 23, marginBottom: 8, marginLeft: 4 }, keyCard: { padding: 16 }, label: { color: palette.muted, fontSize: 11, lineHeight: 15, fontWeight: "800", letterSpacing: 0.8 }, username: { color: palette.indigo, fontSize: 15, lineHeight: 20, fontWeight: "800", marginTop: 2, marginBottom: 17 }, fingerprint: { color: palette.ink, fontFamily: "monospace", fontSize: 16, lineHeight: 23, fontWeight: "800", marginTop: 5 }, loader: { alignSelf: "flex-start", marginTop: 9, marginBottom: 6 }, caption: { color: palette.muted, fontSize: 12, lineHeight: 17, marginTop: 12 }, steps: { paddingVertical: 4 }, step: { flexDirection: "row", alignItems: "flex-start", gap: 11, paddingHorizontal: 15, paddingVertical: 12 }, stepNumber: { width: 25, height: 25, borderRadius: 9, backgroundColor: palette.indigoSoft, alignItems: "center", justifyContent: "center" }, stepNumberText: { color: palette.indigo, fontSize: 12, lineHeight: 16, fontWeight: "800" }, stepText: { flex: 1, color: palette.ink, fontSize: 13, lineHeight: 19 }, note: { color: "#7E889B", fontSize: 12, lineHeight: 17, marginHorizontal: 5, marginTop: 15 }, pressed: { opacity: 0.7 } });
