import { MaterialIcons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { Avatar, palette } from "@/components/meshline-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useMeshline } from "@/lib/meshline-context";

export default function ContactsScreen() {
  const router = useRouter();
  const { ready, isAuthenticated, identity, state, startConversation } = useMeshline();
  const [query, setQuery] = useState("");
  useEffect(() => { if (ready && (!identity || !isAuthenticated)) router.replace("/welcome"); }, [identity, isAuthenticated, ready, router]);
  const contacts = useMemo(() => state.contacts.filter((contact) => `${contact.displayName} ${contact.username}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => a.displayName.localeCompare(b.displayName)), [query, state.contacts]);
  if (!ready || !identity || !isAuthenticated) return <ScreenContainer className="items-center justify-center"><ActivityIndicator color={palette.indigo} /></ScreenContainer>;
  const openContact = async (username: string) => { const conversationId = await startConversation(username); router.push({ pathname: "/chat/[id]", params: { id: conversationId } }); };

  return <ScreenContainer edges={["top", "left", "right"]} containerClassName="bg-[#F6F7FB]" className="bg-[#F6F7FB]"><FlatList data={contacts} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<><View style={styles.header}><View><Text style={styles.title}>Contacts</Text><Text style={styles.subtitle}>Saved locally on this device</Text></View><Pressable onPress={() => router.push("/new-chat")} style={({ pressed }) => [styles.add, pressed && styles.pressed]}><MaterialIcons name="person-add-alt-1" size={20} color="#FFFFFF" /></Pressable></View><View style={styles.search}><MaterialIcons name="search" size={20} color="#8B95A7" /><TextInput value={query} onChangeText={setQuery} placeholder="Search contacts" placeholderTextColor="#8B95A7" style={styles.searchInput} /></View><Text style={styles.label}>PEOPLE</Text></>} renderItem={({ item }) => <Pressable onPress={() => void openContact(item.username)} style={({ pressed }) => [styles.row, pressed && styles.pressed]}><Avatar label={item.displayName} size={48} tone="emerald" /><View style={styles.copy}><Text style={styles.name}>{item.displayName}</Text><Text style={styles.username}>{item.username}</Text></View><MaterialIcons name="chevron-right" size={22} color="#A0A9B9" /></Pressable>} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="people-outline" size={31} color="#A6AFBF" /><Text style={styles.emptyTitle}>No contacts yet</Text><Text style={styles.emptyText}>Save a name and @username to start a private text conversation.</Text><Pressable onPress={() => router.push("/new-chat")} style={({ pressed }) => [styles.emptyAction, pressed && styles.pressed]}><Text style={styles.emptyActionText}>Add contact</Text></Pressable></View>} /></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { padding: 18, paddingTop: 10, paddingBottom: 120, flexGrow: 1 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 18 }, title: { color: palette.ink, fontSize: 28, lineHeight: 34, fontWeight: "800", letterSpacing: -0.55 }, subtitle: { color: palette.muted, fontSize: 13, lineHeight: 18, marginTop: 1 }, add: { width: 42, height: 42, borderRadius: 15, backgroundColor: palette.indigo, alignItems: "center", justifyContent: "center" }, search: { height: 45, backgroundColor: "#ECEFF5", borderRadius: 14, flexDirection: "row", alignItems: "center", gap: 8, paddingHorizontal: 13 }, searchInput: { flex: 1, height: "100%", color: palette.ink, fontSize: 16 }, label: { color: "#8B95A7", fontSize: 11, lineHeight: 16, fontWeight: "800", letterSpacing: 1.05, marginTop: 22, marginBottom: 8, marginLeft: 4 }, row: { minHeight: 68, borderBottomColor: "#E8EBF3", borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", alignItems: "center", gap: 12, paddingVertical: 10 }, copy: { flex: 1 }, name: { color: palette.ink, fontSize: 16, lineHeight: 21, fontWeight: "700" }, username: { color: palette.muted, fontSize: 13, lineHeight: 18, marginTop: 1 }, empty: { alignItems: "center", paddingHorizontal: 35, paddingTop: 55 }, emptyTitle: { color: palette.ink, fontSize: 18, lineHeight: 24, fontWeight: "800", marginTop: 11 }, emptyText: { color: palette.muted, fontSize: 14, lineHeight: 20, textAlign: "center", marginTop: 5 }, emptyAction: { paddingHorizontal: 17, paddingVertical: 10, borderRadius: 13, backgroundColor: palette.indigoSoft, marginTop: 17 }, emptyActionText: { color: palette.indigo, fontSize: 14, lineHeight: 19, fontWeight: "800" }, pressed: { opacity: 0.68 } });
