import { MaterialIcons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";

import { Avatar, palette } from "@/components/meshline-ui";
import { ScreenContainer } from "@/components/screen-container";
import { useMeshline } from "@/lib/meshline-context";
import { useColors } from "@/hooks/use-colors";

export default function ContactsScreen() {
  const router = useRouter();
  const { ready, isAuthenticated, identity, state, startConversation } = useMeshline();
  const colors = useColors();
  const [query, setQuery] = useState("");
  useEffect(() => { if (ready && (!identity || !isAuthenticated)) router.replace("/welcome"); }, [identity, isAuthenticated, ready, router]);
  const contacts = useMemo(() => state.contacts.filter((contact) => `${contact.displayName} ${contact.username}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => a.displayName.localeCompare(b.displayName)), [query, state.contacts]);
  if (!ready || !identity || !isAuthenticated) return <ScreenContainer className="items-center justify-center"><ActivityIndicator color={palette.indigo} /></ScreenContainer>;
  const openContact = async (username: string) => { const conversationId = await startConversation(username); router.push({ pathname: "/chat/[id]", params: { id: conversationId } }); };

  return <ScreenContainer edges={["top", "left", "right"]}><FlatList data={contacts} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<><View style={styles.header}><View><Text style={[styles.title, { color: colors.text }]}>Contacts</Text><Text style={[styles.subtitle, { color: colors.muted }]}>Saved locally on this device</Text></View><Pressable onPress={() => router.push("/new-chat")} style={({ pressed }) => [styles.add, { backgroundColor: colors.tint }, pressed && styles.pressed]}><MaterialIcons name="person-add-alt-1" size={23} color="#FFFFFF" /></Pressable></View><View style={[styles.search, { backgroundColor: colors.surface, borderColor: colors.border }]}><MaterialIcons name="search" size={22} color={colors.muted} /><TextInput value={query} onChangeText={setQuery} placeholder="Search contacts" placeholderTextColor={colors.muted} style={[styles.searchInput, { color: colors.text }]} /></View><Text style={[styles.label, { color: colors.muted }]}>PEOPLE</Text></>} renderItem={({ item }) => <Pressable onPress={() => void openContact(item.username)} style={({ pressed }) => [styles.row, { borderBottomColor: colors.border }, pressed && styles.pressed]}><Avatar label={item.displayName} size={50} tone="emerald" /><View style={styles.copy}><Text style={[styles.name, { color: colors.text }]}>{item.displayName}</Text><Text style={[styles.username, { color: colors.muted }]}>{item.username}</Text></View><MaterialIcons name="chevron-right" size={22} color={colors.muted} /></Pressable>} ListEmptyComponent={<View style={styles.empty}><MaterialIcons name="people-outline" size={34} color={colors.muted} /><Text style={[styles.emptyTitle, { color: colors.text }]}>No contacts yet</Text><Text style={[styles.emptyText, { color: colors.muted }]}>Save a name and @username to start a private text conversation.</Text><Pressable onPress={() => router.push("/new-chat")} style={({ pressed }) => [styles.emptyAction, { backgroundColor: `${colors.tint}22` }, pressed && styles.pressed]}><Text style={[styles.emptyActionText, { color: colors.tint }]}>Add contact</Text></Pressable></View>} /></ScreenContainer>;
}

const styles = StyleSheet.create({ content: { padding: 18, paddingTop: 10, paddingBottom: 120, flexGrow: 1 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 18 }, title: { fontSize: 28, lineHeight: 34, fontWeight: "800", letterSpacing: -0.55 }, subtitle: { fontSize: 13, lineHeight: 18, marginTop: 1 }, add: { width: 52, height: 52, borderRadius: 17, alignItems: "center", justifyContent: "center" }, search: { height: 56, borderRadius: 18, borderWidth: 1, flexDirection: "row", alignItems: "center", gap: 10, paddingHorizontal: 16 }, searchInput: { flex: 1, height: "100%", fontSize: 17 }, label: { fontSize: 11, lineHeight: 16, fontWeight: "800", letterSpacing: 1.05, marginTop: 22, marginBottom: 8, marginLeft: 4 }, row: { minHeight: 74, borderBottomWidth: StyleSheet.hairlineWidth, flexDirection: "row", alignItems: "center", gap: 12, paddingVertical: 11 }, copy: { flex: 1 }, name: { fontSize: 16, lineHeight: 21, fontWeight: "700" }, username: { fontSize: 13, lineHeight: 18, marginTop: 1 }, empty: { alignItems: "center", paddingHorizontal: 35, paddingTop: 55 }, emptyTitle: { fontSize: 18, lineHeight: 24, fontWeight: "800", marginTop: 11 }, emptyText: { fontSize: 14, lineHeight: 20, textAlign: "center", marginTop: 5 }, emptyAction: { paddingHorizontal: 19, paddingVertical: 12, borderRadius: 14, marginTop: 17 }, emptyActionText: { fontSize: 15, lineHeight: 20, fontWeight: "800" }, pressed: { opacity: 0.68 } });
